name: CI

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'     
        required: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run scraper
    - run: npm run build
    - run: npm run export
    - run: cp -r data/ out/
    - uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: out
        GH_PAT: ${{ secrets.GH_PAT }}